apiVersion: v1
kind: Pod
metadata:
   name: overprivilegedpod
spec:
   serviceAccountName: overprivilegedsa
   containers:
   - name: hello-app
     image: gcr.io/google-samples/hello-app:1.0
     args:
     - sleep
     - "1000000"
