---
apiVersion: v1
kind: Pod
metadata:
  name: overprivilegedpod
  namespace: vault
spec:
  serviceAccountName: overprivilegedsa
  containers:
    - command:
        - sleep
        - "3600"
      image: busybox
      name: pods-simple-container
