apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
   name: read-pods
   namespace: vault
subjects:
- kind: ServiceAccount
   name: overprivilegedsa 
   namespace: vault
roleRef:
   kind: Role 
   name: pod-reader 
   apiGroup: rbac.authorization.k8s.io
